In [0]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout ,Conv2D , MaxPooling2D , Flatten
from tensorflow.keras.datasets import mnist
from keras.utils import np_utils

In [3]:
(x_train,y_train) , (x_test,y_test) = mnist.load_data()

11493376/11490434 [==============================] - 0s 0us/step


In [4]:
x_train.shape

(60000, 28, 28)

In [5]:
y_train.shape

(60000,)

In [0]:
x_train = x_train.reshape(x_train.shape[0],x_train.shape[1],x_train.shape[2],1)
x_test = x_test.reshape(x_test.shape[0],x_test.shape[1],x_test.shape[2],1)

In [0]:
x_train=x_train/255
x_test=x_test/255

In [8]:
x_train.shape

(60000, 28, 28, 1)

In [9]:
import numpy as np
np.unique(y_train)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [0]:
y_train = np_utils.to_categorical(y_train,10)
y_test = np_utils.to_categorical(y_test,10)

In [11]:
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [0]:
model = Sequential()
model.add(Conv2D(32, (3,3),activation='relu',input_shape=(28,28,1))) 
model.add(MaxPooling2D(2,2))
model.add(Flatten())
model.add(Dense(32, activation='relu'))
model.add(Dense(10,activation='softmax'))


In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 26, 26, 32)        320       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 13, 13, 32)        0         
_________________________________________________________________
flatten (Flatten)            (None, 5408)              0         
_________________________________________________________________
dense (Dense)                (None, 32)                173088    
_________________________________________________________________
dense_1 (Dense)              (None, 10)                330       
Total params: 173,738
Trainable params: 173,738
Non-trainable params: 0
_________________________________________________________________


In [0]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [16]:
model.fit(x_train,y_train,batch_size=200,epochs=10,validation_data=(x_test,y_test))

Epoch 1/10
300/300 [==============================] - 1s 4ms/step - loss: 0.3938 - accuracy: 0.8873 - val_loss: 0.1619 - val_accuracy: 0.9545
Epoch 2/10
300/300 [==============================] - 1s 3ms/step - loss: 0.1275 - accuracy: 0.9638 - val_loss: 0.0990 - val_accuracy: 0.9702
Epoch 3/10
300/300 [==============================] - 1s 4ms/step - loss: 0.0855 - accuracy: 0.9759 - val_loss: 0.0721 - val_accuracy: 0.9773
Epoch 4/10
300/300 [==============================] - 1s 3ms/step - loss: 0.0691 - accuracy: 0.9805 - val_loss: 0.0631 - val_accuracy: 0.9795
Epoch 5/10
300/300 [==============================] - 1s 3ms/step - loss: 0.0569 - accuracy: 0.9834 - val_loss: 0.0567 - val_accuracy: 0.9794
Epoch 6/10
300/300 [==============================] - 1s 3ms/step - loss: 0.0490 - accuracy: 0.9856 - val_loss: 0.0540 - val_accuracy: 0.9814
Epoch 7/10
300/300 [==============================] - 1s 3ms/step - loss: 0.0435 - accuracy: 0.9870 - val_loss: 0.0498 - val_accuracy: 0.9836
Epoch 

In [17]:
model.evaluate(x_test,y_test)

313/313 [==============================] - 1s 2ms/step - loss: 0.0501 - accuracy: 0.9831


[0.050101689994335175, 0.9830999970436096]

In [18]:
np.argmax(model.predict(x_test),axis=-1)

array([7, 2, 1, ..., 4, 5, 6])

In [19]:
model.predict(x_test)

array([[2.0815574e-09, 1.7056490e-08, 1.4465576e-07, ..., 9.9999523e-01,
        3.6217591e-07, 1.3380473e-07],
       [1.4214237e-06, 1.7258346e-03, 9.9826705e-01, ..., 1.8769170e-11,
        3.4358145e-08, 2.0628148e-10],
       [1.2307270e-05, 9.9925095e-01, 4.4189346e-05, ..., 1.6377143e-04,
        2.4856245e-05, 4.7936214e-07],
       ...,
       [1.6976965e-11, 1.7641454e-09, 6.0812390e-11, ..., 2.8158547e-06,
        1.3680077e-06, 1.3483756e-06],
       [3.8247069e-11, 3.1716962e-10, 1.2078998e-10, ..., 1.2492388e-10,
        1.1648976e-04, 1.6389128e-08],
       [7.1467969e-09, 1.1565396e-09, 6.5213626e-08, ..., 5.7544672e-12,
        5.5470872e-09, 2.5452921e-12]], dtype=float32)